python Test.py  --arch 'STAM'\
                --dataset 'mars'\
                --model_spatial_pool 'avg'\
                --model_temporal_pool 'avg'\
                --train_sampler 'Begin_interval'\
                --test_sampler 'dense'\
                --transform_method 'consecutive'\
                --sampler_method 'random'\
                --triplet_distance 'cosine'\
                --test_distance 'cosine'\
                --is_cat 'yes'\
                --feature_method 'cat'\
                --is_mutual_channel_attention 'yes'\
                --is_mutual_spatial_attention 'yes'\
                --is_appearance_channel_attention 'yes'\
                --is_appearance_spatial_attention 'yes'\
                --layer_num 3 \
                --seq_len 8 \
                --is_down_channel 'no'\
                --print_performance True\
                --layer_name 'down_channel'\
                --test_path '/home/wyq/exp/ablation experiment/2021-09-16_00-54-29/rank1_0.9080808_checkpoint_ep320.pth'